FROM debian:bookworm-slim
# FROM --platform=linux/amd64 debian:bookworm-slim
  
# Install system dependencies
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    wget \
    git \
    screen \
    unzip \
    vim \
    procps \
    locales \
    python3-pip \
 && apt-get clean

# Code server
# https://github.com/coder/code-server/releases
ARG VERSION=4.18.0
# linux-amd64, linux-arm64, linux-armv7l, macos-amd64
ARG PLATFORM=linux-amd64

RUN mkdir -p ~/.local/lib ~/.local/bin
RUN curl -sfL https://github.com/cdr/code-server/releases/download/v$VERSION/code-server-$VERSION-$PLATFORM.tar.gz | tar -C ~/.local/lib -xz
RUN mv ~/.local/lib/code-server-$VERSION-$PLATFORM ~/.local/lib/code-server-$VERSION
RUN ln -s ~/.local/lib/code-server-$VERSION/bin/code-server /usr/local/bin/code-server

# # Miniconda
# RUN curl -sfL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o Miniconda3-latest-Linux-x86_64.sh
# RUN bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/.local/miniconda
# RUN ln -s ~/.local/miniconda/bin/conda /usr/local/bin/conda

WORKDIR /app
ENV SHELL /bin/bash
CMD /usr/local/bin/code-server --cert --bind-addr 0.0.0.0:8080 /app

# docker run --rm --privileged aptman/qus -s -- -p

# docker build -t codeserver-vsait -f Dockerfile_vscs .
# docker run --name codeserver-vsait -v $(pwd):/app -p 8080-8089:8080-8089 -it -d codeserver-vsait
# docker run --name codeserver-vsait --ipc host --gpus all -v $(pwd):/app -p 8080-8089:8080-8089 -it -d codeserver-vsait
# docker exec -it codeserver-vsait cat /root/.config/code-server/config.yaml

